export const SUBMIT_BUTTON='[data-testid="submit-button"]'
export const POPULATE_BUTTON='[data-testid="populate-button"]'
export const NAME_INPUT='[data-testid="name-input"]'
export const THANKYOU_HEADER='[data-testid="thank-you-header"]'
export const TESTCAFE_INTERFACE_SELECT='[data-testid="preferred-interface-select"]'
